config/routes.rb
Dunamis::Application.routes.draw do

  
  resources :paginas

  resources :alertas do
    collection do
      get 'descargas'
    end
  end
  resources :tipos_alertas

  resources :usuarios

  resources :partidos

  resources :tipos_webnotas

  resources :posts

  resources :notas

  resources :tipos_notas

  resources :resumenes do
    collection do
      get 'paso1'
      get 'paso2'
      get 'unir'
      get 'separar'
      get 'descargar'      
    end
    resources :notas
    collection do
      get 'paso1'
      post 'paso1_guardar'
      get 'paso2'
      post 'paso2_guardar'
    end
  end

  resources :candidatos

  resources :tipos_cargos

  resources :municipios

  resources :voceros

  resources :elecciones

  

  resources :informes do
    collection do
      get 'enviar_por_correo'
      get 'paso1'
      get 'paso2'
      get 'paso2b'
      get 'paso3'
      get 'paso4'
      get 'paso5'
      get 'paso6'
      post 'agregar'
      get 'paso3_guardar'
      post 'desagregar_resumen'
    end
    resources :resumenes
  end

  resources :asuntos do
    resources :temas
  end

  resources :temas do
    resources :resumenes
  end

  resources :websites do
    collection do
      get 'barrer'
    end

    resources :paginas
  end

  resources :apariciones

  resources :cunas

  resources :organizaciones do
    match 'actualizar_select_municipios', :action => 'actualizar_select_municipios'
  end

  resources :estados do
    resources :municipios
  end

  resources :candidates

  get "home/index"

  match 'generar_reporte' => 'candidates#generar_reporte', :as => :generar_reporte
  
  match 'organizaciones/actualizar_select_municipios', :controller => 'organizaciones', :action => 'actualizar_select_municipios'

  root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/alerta.rb
class Alerta < ActiveRecord::Base
  attr_accessible :contenido, :resumen, :fecha, :tema_id, :tipo_alerta_id, :vocero_id
  
  belongs_to :tema,
  :class_name => 'Tema',
  :foreign_key => ['tema_id']
  accepts_nested_attributes_for :tema
  
  belongs_to :tipo_alerta,
  :class_name => 'TipoAlerta',
  :foreign_key => ['tipo_alerta_id']
  
  belongs_to :vocero,
  :class_name => 'Vocero',
  :foreign_key => ['vocero_id']

  validates_uniqueness_of :contenido

end

app/controllers/alertas_controller.rb
# encoding: utf-8
class AlertasController < ApplicationController
  # GET /alertas
  # GET /alertas.json
  before_filter :filtro_logueado

  def descargas

    ids = params[:id]
    alertas = Alerta.where(:id => ids.split(","))
    file_name = Pdf.descargar_alertas_excel(alertas)
    send_file file_name, :type => "application/vnd.ms-excel", :filename => "reporte_alertas.xls", :stream => false

    File.delete(file_name)
  end
  
  def index
    @alertas = Alerta.order('fecha DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @alertas }
    end
  end

  # GET /alertas/1
  # GET /alertas/1.json
  def show
    @alerta = Alerta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @alerta }
    end
  end

  # GET /alertas/new
  # GET /alertas/new.json
  def new
    @alerta = Alerta.new
    
    @tipos_alertas = TipoAlerta.all
    @tema = Tema.new
    @voceros = Vocero.all
    @vocero = Vocero.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @alerta }
    end
  end

  # GET /alertas/1/edit
  def edit
    @alerta = Alerta.find(params[:id])
    @tipos_alertas = TipoAlerta.all
    @tema = Tema.new
    @voceros = Vocero.all
    @vocero = Vocero.new
  end

  # POST /alertas
  # POST /alertas.json
  def create
    @alerta = Alerta.new(params[:alerta])

    respond_to do |format|
      if @alerta.save
        format.html { redirect_to @alerta, notice: 'Alerta registrada.' }
        format.json { render json: @alerta, status: :created, location: @alerta }
      else
        @tipos_alertas = TipoAlerta.all
        @tema = Tema.new
        @voceros = Vocero.all
        @vocero = Vocero.new
        flash[:alert] = ""
        @alerta.errors.full_messages.each do |msg|
          flash[:alert] += msg
        end
        
        format.html { render action: "new" }
        format.json { render json: @alerta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /alertas/1
  # PUT /alertas/1.json
  def update
    @alerta = Alerta.find(params[:id])

    respond_to do |format|
      if @alerta.update_attributes(params[:alerta])
        format.html { redirect_to @alerta, notice: 'Alerta actualizada correctamente.' }
        format.json { head :no_content }
      else
        @tipos_alertas = TipoAlerta.all
        @tema = Tema.new
        @voceros = Vocero.all
        @vocero = Vocero.new
        format.html { render action: "edit" }
        format.json { render json: @alerta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alertas/1
  # DELETE /alertas/1.json
  def destroy
    @alerta = Alerta.find(params[:id])
    @alerta.destroy
    flash[:alert] = "La alerta ha sido eliminada"
    respond_to do |format|
      format.html { redirect_to alertas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/alertas_helper.rb
module AlertasHelper
end

app/views/alertas/_filtro_contenido.html.erb
<div class='label label-info' style='float:right;'>
	<a id="text" style='color:white;'></a>
	<%= text_field_tag 'filtro', nil ,{:onkeyup => "return filtrar()", :placeholder=>"Filtrar...", :autofocus => true}%>
</div>
<script type="text/javascript" charset="utf-8">
	function filtrar() {
		var filtro = document.getElementById("filtro").value.toLowerCase();
		var total_mach = 0
		ids = ""
		$("tr.filtrables").each(function(){
			var temp = $(this).text().toLowerCase();
			if (temp.match(filtro) == null) {
				$(this).hide();
			}else {
				$(this).show();
				total_mach += 1;
				ids = ids + $(this).find('td').first().text() + ",";
			}
			
		});
		$("#text").text(total_mach+" coincidencias (Descargar Excel)");
		$("#text").attr('href', "/alertas/descargas?id="+ids)
		return false;
		}
</script>

app/views/alertas/_form.html.erb
<%= form_for @alerta , :html => { :class => 'form-horizontal' }  do |f| %>

  <div class="control-group">
    <%= f.label :fecha, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :fecha, {},{:class => 'span1', :required => true} %>
	  	<span class="help-inline">*</span>
    </div>
  </div>


  <div class="control-group">
    <%= f.label :tema_id, :class => 'control-label' %>
    <div class="controls">
		  <%= f.grouped_collection_select :tema_id, Asunto.all, :temas, :nombre, :id, :nombre, {:prompt => "Tema"}, { :class => 'selects2 span3'} %>

			<%= link_to (""), { :role => 'button',:class => 'btn btn-success btn-mini', :data => {:toggle => 'modal'}, :onclick => "return $('#tema_nuevo').modal();"} do %>
				<i class="icon-plus icon-white"></i>
				<i class="icon-th-list icon-white"></i>
			<% end %>
			<span class="help-inline">*</span>
    </div>
  </div>


  <div class="control-group">
		<%= f.label :vocero_id, :class => 'control-label' %>
		<div class='controls'>
			<%# f.collection_select :vocero_id, Vocero.order('nombre ASC'), :id, :descripcion_completa, {:prompt => "Vocero"}, {:required => true, :onChange => "mostrar_edit();", :class => 'selects2 span3'} %>
			<%= f.collection_select :vocero_id, Vocero.order('nombre ASC'), :id, :descripcion_completa, {:prompt => "Vocero"}, {:required => true, :style => 'width: 50%;', :onChange => "mostrar_edit();"} %>
			<%# f.collection_select :vocero_id, Vocero.order('nombre ASC'), :id, :nombre_descripcion, {:prompt => "Vocero"}, {:required => true, :onChange => "return mostrar_edit();", :class => 'selects2 span3'} %>
			<b class='tooltip-btn' data_toggle='tooltip' title='Editar Vocero' >
				<%= link_to (""), { :role => 'button',:class => 'btn btn-info btn-mini', :id => 'boton_editar_vocero', :style => 'display: none;', :data => {:toggle => 'modal'}, :onclick => "return form_editar_vocero();"} do %>
					<%= content_tag(:i, "", class: "icon-edit icon-white") %>
					<%= content_tag(:i, "", class: "icon-user icon-white") %>
				<% end %>
			</b>

			<b class='tooltip-btn' data_toggle='tooltip' title='Agregar Nuevo Vocero' >
				<%= link_to (""), { :role => 'button', :class => 'btn btn-success btn-mini', :data => {:toggle => 'modal'}, :onclick => "return $('#vocero_nuevo').modal();"} do %>
					<%= content_tag(:i, "", class: "icon-plus icon-white") %>
					<%= content_tag(:i, "", class: "icon-user icon-white") %>
				<% end %>
			</b>
			<span class="help-inline">*</span>
		</div>
  </div>

  <div class="control-group">
    <%= f.label :contenido, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :contenido, :class => 'text_field', :required => true %>
	  	<span class="help-inline">*</span>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :resumen, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :resumen, :class => 'text_area span3', :size => '5x5', :required => true %>
	  	<span class="help-inline">*</span>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :tipo_alerta_id, :class => 'control-label' %>
    <div class="controls">
			<%= f.collection_select :tipo_alerta_id, @tipos_alertas, :id, :descripcion, {:prompt => "Tipo de Alerta"}, {:required => true, :class => "selects2 span3"} %>
    	<span class="help-inline">*</span>
		</div>
  </div>


  <div class="form-actions">
		<%= link_to 'Regresar', alertas_path, :class => 'btn' %>
    ||
		<%= f.submit nil, :class => 'btn btn-primary', data: { :disable_with => "Por favor espere..." } %>
  </div>
<% end %>


<%= render 'voceros/editar_vocero_modal' %>

<%- @url = request.original_url %>

<div id="vocero_nuevo" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
 <div class="modal-header">
   <button type="button" class="close fade" data-dismiss="modal" aria-hidden="true">×</button>
   <h3 id="myModalLabel">Nuevo Vocero</h3>
 </div>
 <div class="modal-body">
   <%= render 'voceros/form', :@url => @url %>
 </div>
</div>

<div id="tema_nuevo" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close fade" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Nuevo Tema</h3>
  </div>
  <div class="modal-body">
    <%= render :partial => 'temas/form' %>

  </div>
</div>


<script type="text/javascript" charset="utf-8">


	function format(vocero) {
	    return vocero.text;
	}
	$("#alerta_vocero_id").select2({
	    formatResult: format,
	    formatSelection: format,
	    escapeMarkup: function(m) { return m; }
	});
	
	function mostrar_edit(){
		// document.getElementById("boton_editar_vocero").style.display="inline-block";
		$('#boton_editar_vocero').show('slow');
	}
	
	function form_editar_vocero(){
		
		var vocero_selected = $("#alerta_vocero_id");

		// document.getElementById("vocero_nombre").value = vocero_selected.text();
		
		if (vocero_selected.val()==39) {
			$('#otro_vocero').show('slow');
		}
		
		document.getElementById("boton_editar_vocero").action="/voceros/update/"+vocero_selected.val();
		$('#vocero_editar').modal();
		return false;
	}
	
	function eliminar_nota(nota_id, resumen_id){
		$.post('/notas/update/'+nota_id+"?resumen_id=-1");
		$.post("/resumenes/update/"+resumen_id+"?nota_id="+nota_id+"&borrar_nota_en_contenido=1");
		location.reload();
		return false;
	}
	
	$(document).ready(function() {
		$('.tooltip-btn').tooltip();
		$(".selects2").select2();
	});
</script>

app/views/alertas/edit.html.erb
<h1>Editing alerta</h1>

<%= render 'form' %>

<%= link_to 'Show', @alerta %> |
<%= link_to 'Back', alertas_path %>

app/views/alertas/index.html.erb
<%= link_to 'Nueva Alerta', new_alerta_path, :class => 'btn btn-primary' %>
<h1>Alertas</h1>

<%= render :partial => 'filtro_contenido'%>


<table class = 'table table-striped table-bordered table-hover table-condensed'>
  <tr>
		<th>Id</th>
    <th>Fecha</th>
    <th>Contenido</th>
    <th style="width:50%;" >Resumen</th>
    <th>Temas</th>
    <th>Tipos alertas</th>
    <th>Voceros</th>
    <th>Opciones</th>
  </tr>

<% @alertas.each do |alerta| %>
  <tr class='filtrables'>
	  <td>
			<b class='tooltip-btn' data_toggle='tooltip' title='Ver Alerta' >
				<%= link_to alerta.id, alerta %></td>
			</b>
    <td><%= alerta.fecha %></td>
    <td><%= alerta.contenido %></td>
		<td><%= alerta.resumen %></td>
    <td><%= alerta.tema.full_descripcion %></td>
    <td><%= alerta.tipo_alerta.descripcion.capitalize %></td>
    <td><%= alerta.vocero.nombre_descripcion %></td>
    <td>
			<b class='tooltip-btn' data_toggle='tooltip' title='Editar Alerta' >
				<%= link_to edit_alerta_path(alerta), { :role => 'button', :class => 'btn btn-info btn-mini'} do %>
					<%= content_tag(:i, "", class: "icon-edit icon-white") %>
				<% end %>
			</b>	

			<b class='tooltip-btn' data_toggle='tooltip' title='Eliminar Alerta' >
				<%= link_to alerta_path(alerta), { :role => 'button', :class => 'btn btn-danger btn-mini', :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Estas seguro de esta acción?')) }} do %>
					<%= content_tag(:i, "", class: "icon-trash icon-white") %>
				<% end %>
			</b>
    </td>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nueva Alerta', new_alerta_path, :class => 'btn btn-primary' %>


<script type="text/javascript" charset="utf-8">
	$(document).ready(function() {
		$('.tooltip-btn').tooltip();
	});
</script>

app/views/alertas/new.html.erb
<%- model_class = Alerta -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/alertas/show.html.erb
<%- model_class = Alerta -%>
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:fecha) %>:</strong></dt>
  <dd><%= @alerta.fecha %></dd>
  <dt><strong><%= model_class.human_attribute_name(:vocero_id) %>:</strong></dt>
  <dd><%= @alerta.vocero.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tema_id) %>:</strong></dt>
  <dd><%= @alerta.tema.full_descripcion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contenido) %>:</strong></dt>
  <dd><%= @alerta.contenido %></dd>
  <dt><strong><%= model_class.human_attribute_name(:resumen) %>:</strong></dt>
  <dd><%= @alerta.resumen %></dd>

</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              alertas_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_alerta_path(@alerta), :class => 'btn btn-info' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              alerta_path(@alerta),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>