config/routes.rb
Dunamis::Application.routes.draw do

  
  resources :paginas

  resources :alertas do
    collection do
      get 'descargas'
    end
  end
  resources :tipos_alertas

  resources :usuarios

  resources :partidos

  resources :tipos_webnotas

  resources :posts

  resources :notas

  resources :tipos_notas

  resources :resumenes do
    collection do
      get 'paso1'
      get 'paso2'
      get 'unir'
      get 'separar'
      get 'descargar'      
    end
    resources :notas
    collection do
      get 'paso1'
      post 'paso1_guardar'
      get 'paso2'
      post 'paso2_guardar'
    end
  end

  resources :candidatos

  resources :tipos_cargos

  resources :municipios

  resources :voceros

  resources :elecciones

  

  resources :informes do
    collection do
      get 'enviar_por_correo'
      get 'paso1'
      get 'paso2'
      get 'paso2b'
      get 'paso3'
      get 'paso4'
      get 'paso5'
      get 'paso6'
      post 'agregar'
      get 'paso3_guardar'
      post 'desagregar_resumen'
    end
    resources :resumenes
  end

  resources :asuntos do
    resources :temas
  end

  resources :temas do
    resources :resumenes
  end

  resources :websites do
    collection do
      get 'barrer'
    end

    resources :paginas
  end

  resources :apariciones

  resources :cunas

  resources :organizaciones do
    match 'actualizar_select_municipios', :action => 'actualizar_select_municipios'
  end

  resources :estados do
    resources :municipios
  end

  resources :candidates

  get "home/index"

  match 'generar_reporte' => 'candidates#generar_reporte', :as => :generar_reporte
  
  match 'organizaciones/actualizar_select_municipios', :controller => 'organizaciones', :action => 'actualizar_select_municipios'

  root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/asunto.rb
class Asunto < ActiveRecord::Base
  attr_accessible :descripcion, :nombre
  
  has_many :temas, :dependent => :destroy
  accepts_nested_attributes_for :temas
  
  has_many :informes_asuntos, :dependent => :destroy
  accepts_nested_attributes_for :informes_asuntos
  
  
end

app/controllers/asuntos_controller.rb
class AsuntosController < ApplicationController
  # GET /asuntos
  # GET /asuntos.json
  before_filter :filtro_logueado
  
  def index
    @asuntos = Asunto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @asuntos }
    end
  end

  # GET /asuntos/1
  # GET /asuntos/1.json
  def show
    @asunto = Asunto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @asunto }
    end
  end

  # GET /asuntos/new
  # GET /asuntos/new.json
  def new
    @asunto = Asunto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @asunto }
    end
  end

  # GET /asuntos/1/edit
  def edit
    @asunto = Asunto.find(params[:id])
  end

  # POST /asuntos
  # POST /asuntos.json
  def create
    @asunto = Asunto.new(params[:asunto])

    respond_to do |format|
      if @asunto.save
        format.html { redirect_to @asunto, notice: 'Asunto creado satisfactoriamente.' }
        format.json { render json: @asunto, status: :created, location: @asunto }
      else
        format.html { render action: "new" }
        format.json { render json: @asunto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /asuntos/1
  # PUT /asuntos/1.json
  def update
    @asunto = Asunto.find(params[:id])

    respond_to do |format|
      if @asunto.update_attributes(params[:asunto])
        format.html { redirect_to @asunto, notice: 'Asunto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @asunto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asuntos/1
  # DELETE /asuntos/1.json
  def destroy
    @asunto = Asunto.find(params[:id])
    @asunto.destroy

    respond_to do |format|
      format.html { redirect_to asuntos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/asuntos_helper.rb
module AsuntosHelper
end

app/views/asuntos/_form.html.erb
<%= form_for @asunto, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre, :class => 'text_field', :required => true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :descripcion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :descripcion, :class => 'text_area', :size => '5x5' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                asuntos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/asuntos/edit.html.erb
<%- model_class = Asunto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/asuntos/index.html.erb
<%- model_class = Asunto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:descripcion) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @asuntos.each do |asunto| %>
      <tr>
        <td><%= link_to asunto.id, asunto_path(asunto) %></td>
        <td><%= asunto.nombre %></td>
        <td><%= asunto.descripcion %></td>
        <td><%=l asunto.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_asunto_path(asunto), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      asunto_path(asunto),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_asunto_path,
            :class => 'btn btn-primary' %>

app/views/asuntos/new.html.erb
<%- model_class = Asunto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'Nuevo %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/asuntos/show.html.erb
<%- model_class = Asunto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @asunto.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descripcion) %>:</strong></dt>
  <dd><%= @asunto.descripcion %></dd>
</dl>

<h3 id="Temas">Temas</h3>
<% if @asunto.temas %>
	<% @asunto.temas.each do |tema| -%>
		<h6><%= tema.nombre -%></h6>
	<%- end -%>

	<%= form_for([@asunto, @asunto.temas.build]) do |f| %>

  	<div class="control-group">
    	<div class="controls">
				<h6>Agregar tema:
				<%= f.text_field :nombre, :class => 'input-medium', :placeholder => "Nombre…", :required => true %>
    		<%= f.submit nil, :class => 'btn btn-primary' %>
				</h6>
			</div>
  	</div>
	<% end %>
<% end %>


<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              asuntos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_asunto_path(@asunto), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              asunto_path(@asunto),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>