config/routes.rb
Dunamis::Application.routes.draw do

  
  resources :paginas

  resources :alertas do
    collection do
      get 'descargas'
    end
  end
  resources :tipos_alertas

  resources :usuarios

  resources :partidos

  resources :tipos_webnotas

  resources :posts

  resources :notas

  resources :tipos_notas

  resources :resumenes do
    collection do
      get 'paso1'
      get 'paso2'
      get 'unir'
      get 'separar'
      get 'descargar'      
    end
    resources :notas
    collection do
      get 'paso1'
      post 'paso1_guardar'
      get 'paso2'
      post 'paso2_guardar'
    end
  end

  resources :candidatos

  resources :tipos_cargos

  resources :municipios

  resources :voceros

  resources :elecciones

  

  resources :informes do
    collection do
      get 'enviar_por_correo'
      get 'paso1'
      get 'paso2'
      get 'paso2b'
      get 'paso3'
      get 'paso4'
      get 'paso5'
      get 'paso6'
      post 'agregar'
      get 'paso3_guardar'
      post 'desagregar_resumen'
    end
    resources :resumenes
  end

  resources :asuntos do
    resources :temas
  end

  resources :temas do
    resources :resumenes
  end

  resources :websites do
    collection do
      get 'barrer'
    end

    resources :paginas
  end

  resources :apariciones

  resources :cunas

  resources :organizaciones do
    match 'actualizar_select_municipios', :action => 'actualizar_select_municipios'
  end

  resources :estados do
    resources :municipios
  end

  resources :candidates

  get "home/index"

  match 'generar_reporte' => 'candidates#generar_reporte', :as => :generar_reporte
  
  match 'organizaciones/actualizar_select_municipios', :controller => 'organizaciones', :action => 'actualizar_select_municipios'

  root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/nota.rb
class Nota < ActiveRecord::Base
  belongs_to :tipo_nota
  belongs_to :website
  belongs_to :resumen
  
  attr_accessible :contenido, :titulo, :url, :website_id, :tipo_nota_id, :resumen_id, :imagen, :fecha_publicacion
  validates_presence_of :titulo, :url, :website_id, :tipo_nota_id
  validates_uniqueness_of :url
    # validates_associated :tolda, :tipo, :cunas
    
  scope :creadas_hoy, -> {where("created_at >= ?", Date.today)}
  
  scope :creadas_antes, -> {where("created_at < ?", Date.today)}
  
  scope :creadas_hoy_no_incluidas_en_resumen, -> resumen_id {creadas_hoy.validas.where("resumen_id != ? OR resumen_id IS ?", resumen_id, nil)}
  
  # scope :creadas_hoy_sin_resumen, -> {creadas_hoy.validas.where("resumen_id IS ?", nil)}
  scope :con_resumen, -> {where("resumen_id IS NOT ?", nil)}
  
  scope :sin_resumen, -> {where("resumen_id IS ?", nil)}
  
  scope :validas, ->{where(:tipo_nota_id => 2)}
  
  scope :invalidas, ->{where(:tipo_nota_id => 1)}
  
  def valida?
    if tipo_nota_id == 1
      return false
    else
      return true
    end 
  end

  # def validar
  #   tipo_nota_id = 2
  #   if save
  #     return true
  #   else
  #     return false
  #   end
  # end
  # 
  # def invalidar
  #   
  # end
  
  def self.creadas_hoy_no_incluidas (resumen_id)
    creadas_hoy.where("resumen_id != ? OR resumen_id IS ?", resumen_id, nil)    
  end
  
  def descripcion
    "#{website.descripcion} / #{titulo[0..20]}..."
  end
  
end

app/controllers/notas_controller.rb
# encoding: utf-8
class NotasController < ApplicationController
  # GET /notas
  # GET /notas.json
  before_filter :filtro_logueado  
  def index
    @notas = Nota.limit(100).order('created_at ASC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notas }
    end
  end

  # GET /notas/1
  # GET /notas/1.json
  def show
    @nota = Nota.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @nota }
    end
  end

  # GET /notas/new
  # GET /notas/new.json
  def new
    @modal = false
    @nota = Nota.new
    @websites = Website.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nota }
    end
  end

  # GET /notas/1/edit
  def edit
    @nota = Nota.find(params[:id])
  end

  # POST /notas
  # POST /notas.json
  def create
    params[:nota][:contenido] = params[:nota][:contenido].squeeze 
    @nota = Nota.new(params[:nota])

    if params[:url]
      if @nota.save 
        flash[:notice] = 'Nota creada correctamente.'
        # format.json { render json: @nota, status: :created, location: @nota }
      else
        flash[:alert] = ""
        @nota.errors.full_messages.each do |msg|
          flash[:alert] += msg
        end
        # format.json { render json: @nota.errors, status: :unprocessable_entity }
      end
      redirect_to params[:url]
    else
      if @nota.save
        flash[:notice] = 'Nota creada correctamente.'
        redirect_to :back
        # format.json { render json: @nota, status: :created, location: @nota }
      else
        @modal = false
        # @tipo_nota = TipoNota.all
        @websites = Website.all
        flash[:alert] = ""
        @nota.errors.full_messages.each do |msg|
          flash[:alert] += msg
        end
        
        format.html { render action: "new" }
        format.json { render json: @nota.errors, status: :unprocessable_entity }
      end
    end

  end

  # PUT /notas/1
  # PUT /notas/1.json
  def update
    @nota = Nota.find(params[:id])
    
    if params[:resumen_id]
      if params[:resumen_id].eql? "-1"
        @nota.resumen_id = nil
      else
        @nota.resumen_id = params[:resumen_id] 
      end
    end
    @nota.tipo_nota_id = params[:tipo_nota_id] if params[:tipo_nota_id]
    

    respond_to do |format|
      if @nota.update_attributes(params[:nota])
        format.html { redirect_to @nota, notice: 'Nota was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @nota.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notas/1
  # DELETE /notas/1.json
  def destroy
    @nota = Nota.find(params[:id])
    @nota.destroy

    respond_to do |format|
      format.html { redirect_to notas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/notas_helper.rb
# encoding: utf-8
module NotasHelper
  
  def link_nota nota
    link_to nota.website.descripcion, nota.url, {:class => 'btn btn-link', :target => '_blank'}
  end

  def link_descartar_nota nota_id, resumen_id=nil
		link_to "/wizard/invalidar/#{nota_id}?resumen_id=#{resumen_id}&action_name=#{action_name}", :resumen_id => resumen_id, :class => 'btn btn-mini btn-danger', :data => {:confirm => '¿Descartar nota?', :method => 'delete'} do
      raw "<i class='icon-minus icon-file	icon-white'></i>"

		end
  end
  
  def link_borrar_nota nota_id
    link_to "#", {:class => 'btn btn-mini', :onclick => "return eliminar_nota (#{nota_id})"} do
			html_tag(:i, :class => 'icon-trash icon-black')
		end		
  end
  
end

app/views/notas/_detalle.html.erb
<% clase = @nota.valida? ? "success" : "" %>
<tr class= "<%= clase %>">
	<td>	
	<div class="row-fluid" >
		<ul class="media-list">
		  <li class="media">
		    <div class="media-body">
				<!-- <p> -->
					<%# case action_name %>
					<% if action_name.eql? "paso1" %>
					
						<%= check_box_tag "notas_validas_ids[]", @nota.id, @nota.valida?, {:class => "btn", :style => "display:none;"} %>

					<% else %>
						<%= link_descartar_nota @nota.id, @resumen.id %>
					<% end %>
					
					<% if action_name.eql? 'paso3' %>
					|
						<%= link_to ("/wizard/agregar_nota?website_name=#{@website.nombre}&nota_id=#{@nota.id}&resumen_id=#{@resumen.id}&nota=true"), {:class => "btn btn-success btn-mini"} do %>
							<%= content_tag(:i, "", class: "icon-arrow-up icon-white") %> 
						<% end %>
						|
							<%= link_to ("/wizard/agregar_nota?website_name=#{@website.nombre}&nota_id=#{@nota.id}&resumen_id=#{@resumen.id}"), {:class => "btn btn-info btn-mini"} do %>
								<%= content_tag(:i, "", class: "icon-arrow-up icon-white") %> 
							<% end %>						
					<% end %>

		      <b class="media-heading">
						<%- unless @nota.fecha_publicacion.blank? -%>
							<div class="label">
								<%= "#{@nota.fecha_publicacion}: "%>
							</div>
						<% end %>
						<%= @nota.titulo.to_s[0..100] %>
					</b>
					<%- unless @nota.imagen.blank? -%>
						<a class="pull-right">
							<%= image_tag @nota.imagen, :title => "imagen", :class => "media-object img-rounded", :style => 'max-width: 120px; max-height:120px;'%>
				  	</a>
					<% end %>
			    <% unless @nota.contenido.blank? %>
						<div id="contenido_nota<%=@nota.id%>" class="contenido_nota" style = "display: none;">							
							<%= @nota.contenido %>
						</div>
					<% end %>
		    </div>
		  </li>
		</ul>
	</div>
	<div >
		<%= link_nota @nota %>
		<%= link_to "detalle", " ", {:class => 'btn btn-mini', :onclick => "return detalle('#{@nota.id}')"} unless @nota.contenido.blank? %>			
	</div>
</td></tr>


<script type="text/javascript" charset="utf-8">

	function detalle(nota_id){
		if ($('#contenido_nota'+nota_id).css("display") == "none") { 
			$('#contenido_nota'+nota_id).show();
			$(this).hide;

			}
		else{$('#contenido_nota'+nota_id).hide();}
		return false;
	}
	
</script>

app/views/notas/_form.html.erb
<%= form_for @nota, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :titulo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :titulo, :class => 'text_field', :placeholder => "Título…", :required => true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :contenido, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :contenido, :class => 'text_area', :size => '5x5', :placeholder => "Contenido…", :required => true %>
    </div>
  </div>
  <!-- <div class="control-group"> -->
    <%# f.label :tipo_nota_id, :class => 'control-label' %>
    <!-- <div class="controls"> -->
      <%# f.number_field :tipo_nota_id, :class => 'number_field' %>
			<%# f.collection_select :tipo_nota_id, @tipo_nota, :id, :nombre, {:prompt => true}, {:required => true, :class => "selectpicker"} %>
			<%= f.hidden_field :tipo_nota_id, :value => 2 %>
    <!-- </div> -->
  <!-- </div> -->
  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'text_field', :required => true, :placeholder => "Url…" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :website_id, :class => 'control-label' %>
    <div class="controls">
			<%= f.collection_select :website_id, @websites, :id, :nombre, {:prompt => true}, {:required => true, :class => "selectpicker"} %>
    </div>
  </div>
	<%= hidden_field_tag 'url', @url if @url %>
  <!-- <div class="control-group">
    <%# f.label :resumen_id, :class => 'control-label' %>
    <div class="controls">
      <%# f.number_field :resumen_id, :class => 'number_field' %>
    </div>
  </div> -->

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
		<% if @url %>
			<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              "", :class => 'btn', :data => {:dismiss => 'modal'} %>
  	<% else %>
  	  
    	<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                notas_path, :class => 'btn' %>
		<% end %>
  </div>
<% end %>

app/views/notas/_lista.html.erb
<%- paso1 = action_name.eql? 'paso1' -%>
<p class= 'center label label-info'><b><%= @total_notas %> <%= "Nota".pluralize(@total_notas) %> <%= "Disponible".pluralize(@total_notas) %></b>
		<%= render :partial => 'resumenes/filtro_lista' if not paso1%>

		<% if paso1 %>
			<b class='tooltip-btn' data_toggle='tooltip' title= "Puede ser un proceso lento" >
				<%= link_to "", {:href => "/websites/barrer", :class => 'btn btn-mini'}, { :role => 'button', :data => {:toggle => 'modal'}} do %>
					Barrer Todos Los Sitios
					<%= content_tag(:i, "", class: "icon-refresh") %>
				<% end %>
			</b>
		<% end %>
</p>
<%= render :partial => 'panel_website' if paso1 %>


<table class="table-bordered">
	<tr class="info">
			<%- @websites.each_with_index do |website,i| -%>
				<%- contador_notas = website.notas.creadas_hoy %>
				<%- contador_notas = paso1 ? contador_notas.sin_resumen.count : contador_notas.validas.sin_resumen.count %>
				<% seleccionada = website.usuario_id.eql?(session[:usuario].id) %>
				<% if (contador_notas > 0) %>
					<th id="<%= website.nombre %>_titulo" style="background:skyblue; <%= 'display:none;' unless seleccionada %>">
						<%= website.nombre %>
						<span class="badge badge-inverse"><%= contador_notas %></span>
						<% if action_name.eql? "paso1" and controller_name.eql? "wizard" %>
							<b class='tooltip-btn' data_toggle='tooltip' title= "Barrer <%= website.descripcion %> " >
								<%= link_to "", {:href => "/websites/barrer/#{website.id}", :class => 'btn btn-mini'}, { :role => 'button', :data => {:toggle => 'modal'}} do %>
									<%= content_tag(:i, "", class: "icon-refresh") %>
								<% end %>
							</b>
						<% end %>
					</th>
				<% end %>
			
			<% end %>
	</tr>
	<tr>

		<%- @websites.each_with_index do |website,i| -%>

			<% seleccionada = website.usuario_id.eql?(session[:usuario].id) %>

			<%- @notas = website.notas.creadas_hoy.order('updated_at DESC') %>
			<%- @notas = (action_name.eql? 'paso1') ? @notas.sin_resumen : @notas.validas.sin_resumen %>

			<% if @notas.count > 0 %>
				<td id="<%= website.nombre %>" style="<%= 'display:none;' unless seleccionada %>">
					<div class=contenido_scroll>
						<table class="table table-condensed table-striped table-hover notas<%= ' seleccionada' if seleccionada %>">
							<%- @notas.each do |nota| -%>
								<% @nota = nota %>
								<% @website = website %>
									<%= render :partial => 'notas/detalle' %>
							<% end %>
						</table>
					</div>
				</td>
			<% end %>
			
		<% end %>
	</tr>
</table>

<% if paso1 %>
	<script type="text/javascript" charset="utf-8">

		$(document).ready(function(){
		  $("table.seleccionada .row-fluid").click(function(){
				var checkbox = $(this).find(':checkbox');
				checkbox.click();
				if(checkbox.is(':checked')) {  
					$(this).parent().parent().addClass('success');
				}else{
					$(this).parent().parent().removeClass('success');
				}
		   });
		});
	</script>

<% else %>

	<script type="text/javascript" charset="utf-8">

		$(".voceros").select2({
			formatResult: format,
			formatSelection: format,
			escapeMarkup: function(m) { return m; }
		});

	</script>  

<% end %>

app/views/notas/_seleccion.html.erb
<%= form_tag(:action => "#{action_name}_guardar") do %>

<% if action_name == "paso1" %>
	<div class="well well-small" style="text-align: right;">
		<%= submit_tag "Guardar Selección", :id => "submit", :name => "submit", :class => "btn btn-primary", :disabled => false, :disable_with => "Enviando..." %>	
	</div>
<% end %>
<%= hidden_field_tag "website_activa", session[:website_activa] %>
<%= render :partial => 'resumenes/filtro' %>
<div class="control-group">
	<ul id="myTab" class="nav nav-tabs">
	<%- @websites.each_with_index do |website,i| -%>
	 	<li class= "<%=" active" if (website.nombre.eql? session[:website_activa]) %>" style="font-size: 10px;">
			<% case action_name %>
			<% when "paso1" %>
				<% contador_notas = website.notas.creadas_hoy.sin_resumen.count %>
			<% else %>
				<% contador_notas = website.notas.creadas_hoy.validas.sin_resumen.count %>
			<% end %>
			<% if contador_notas > 0 %>
			
				<%= link_to "##{website.nombre}", :data => {:toggle => "tab"}, :onclick => "return set_website_activa('#{website.nombre.to_s}')" do %>
					<%= "#{website.descripcion}" %>
					<span class="badge badge-inverse"><%= contador_notas %></span>
				<% end %>
			<% end %>
	 	</li>
	<%- end -%>
	</ul>
	<div data-spy="scroll" data-target="#myTab" data-offset="0" class="scrollspy-example">
		<div id="myTabContent" class="tab-content">
			<%- @websites.each_with_index do |website,i| -%>
				<%# website.importar_notas_website unless website.carga_reciente? %>
				<% case action_name %>
				<% when "paso1" %>
					<%- @notas = website.notas.creadas_hoy.sin_resumen -%>
				<%# when "paso2" %>
					<%# @notas = website.notas.creadas_hoy_sin_resumen -%>
				<% else %>
					<%- @notas = website.notas.creadas_hoy.validas.sin_resumen -%>
				<% end %>
								
				<div class="tab-pane fade<%=" active in" if (website.nombre.eql? session[:website_activa]) %>" id="<%= website.nombre %>">

					<div style="overflow: scroll;height: 300px;">
						
						<table class="table table-hover">
		        	<thead>
		          	<tr>
			            <th></th>
									<th></th>
									<th width="90px;"></th>
			          </tr>
			        </thead>
			        <tbody>
								<%- @notas.each_with_index do |nota,j| -%>
									
									<%# fondo = 'background-color: honeydew;' if nota.valida? %>
									<tr id="<%=nota.id%>">
										<td><%= j+1 %></td>
										<td>
											<div class="media">
											  <%- unless nota.imagen.blank? -%>
													<a class="pull-left">
														<%= image_tag nota.imagen, :title => "imagen", :class => "media-object img-rounded", :style => 'max-width: 120px; max-height:120px;'%>
											  	</a>
												<% end %>
											  <div class="media-body">
											    <h5 class="media-heading"><%= nota.fecha_publicacion %> : <%= nota.titulo %></h5>
													<%= link_nota nota %>
											    <% unless nota.contenido.blank? %>
														<%= link_to "detalle", " ", {:class => 'btn btn-mini', :onclick => "return detalle('#{nota.id}')"} %>
														<div id="contenido_nota<%=nota.id%>", style = "display: none; text-align: justify;">
															<%= nota.contenido %>
														</div>
													<% end %>
												</div>
											</div>
										</td>
				            <td>
											<% case action_name %>
											<% when "paso1" %>
												<%# etiq = nota.valida? ? "success" : "info" %>
												
												<span class="btn">
													<%= check_box_tag "notas_validas_ids[]", nota.id, nota.valida?, {:class => "btn"} %>
													<%= nota.valida? ? "Inluido" : "Incluir" %>
												</span>
												
												<%# , :onclick => "return pintar_fondo('#{nota.id}');" %>
												
											<% when "paso3" %>
												<%= link_to "/#{controller_name}/invalidar/#{nota.id}?resumen_id=#{@resumen.id}&action_name=#{action_name}", :resumen_id => @resumen.id, :class => 'btn btn-mini btn-danger', :data => {:confirm => '¿Esta Seguro?', :method => 'delete'} do %>
													<i class='icon-trash icon-black'></i>
												<% end %>
												|
												<%= link_to ("/wizard/agregar_nota?website_name=#{website.nombre}&nota_id=#{nota.id}&resumen_id=#{@resumen.id}"), {:class => "btn btn-success btn-mini"} do %>
													<%= content_tag(:i, "", class: "icon-arrow-up icon-white") %> 
												<% end %>
											<% end %>

												<%# select_tag "nota_vocero_ids[#{nota.id}]", options_from_collection_for_select(Vocero.order('nombre DESC'), 'id', 'descripcion_completa' ), :class => 'voceros', prompt: "Seleccione..."%>
										</td>
				          </tr>
								<% end %>
		        	</tbody>
		      	</table>
						
					</div>
				</div> <!-- class="tab-pane fade -->
			<%- end -%>
		</div> <!-- id="myTabContent" -->
	</div> <!-- data-spy="scroll" -->
</div>  <!-- class="bs-docs-example" -->

  
<% end -%>


<script type="text/javascript" charset="utf-8">
	
	
	// function pintar_fondo(nota_id){
	// 	// alert(document.getElementById(nota_id).cells.item(4).setAttribute("checked") );
	// 	var div_nota = document.getElementById(nota_id);
	// 	// div_nota.cells.item(4).innerHTML.click();
	// 	var valor;
	// 
	// 	
	// 	if (div_nota.cells[4].getElementsByName('checkbox')){
	// 		valor = "si"+div_nota.cells[4];
	// 	}else{
	// 		valor = "no"+div_nota.cells[4].getElementsByName('checkbox');
	// 	}
	// 		
	// 	alert(valor);
	// 	div_nota.style.backgroundColor = "honeydew";
	// 	return true;		
	// }
	
	function set_website_activa(nombre_website){
		document.getElementById("website_activa").value = nombre_website;
		return false;
		
	}
	
	function format(vocero) {
		return vocero.text;
	}
	$(".voceros").select2({
		formatResult: format,
		formatSelection: format,
		escapeMarkup: function(m) { return m; }
	});


	function detalle(nota_id){
		if ($('#contenido_nota'+nota_id).css("display") == "none") { $('#contenido_nota'+nota_id).show();}
		else{$('#contenido_nota'+nota_id).hide();}
		return false;
	}

	// function agregar_nota(nombre_website, nota_id, resumen_id){
	// 	$("#"+nota_id).hide();
	// 	$.post("/notas/update/"+nota_id+"?resumen_id="+resumen_id+"&nombre_website"+nombre_website.id);
	// 	$.post("/resumenes/update/"+resumen_id+"?nota_id="+nota_id);
	// 	$.post("/wizard/actualizar_website_activa/"+nombre_website.id);
	// 	// this = this+"#"+website_nombre;
	// 	// location.form.reload();
	// 	// $("#main").reload();
	// 	location.reload();
	// 
	// 	return false;
	// }

	
</script>

app/views/notas/edit.html.erb
<%- model_class = Nota -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/notas/index.html.erb
<%- model_class = Nota -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:titulo) %></th>
      <th><%= model_class.human_attribute_name(:contenido) %></th>
      <th><%= model_class.human_attribute_name(:tipo_nota_id) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:website_id) %></th>
      <th><%= model_class.human_attribute_name(:resumen_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @notas.each do |nota| %>
      <tr>
        <td><%= link_to nota.id, nota_path(nota) %></td>
        <td><%= nota.titulo %></td>
        <td><%= nota.contenido %></td>
        <td><%= nota.tipo_nota_id %></td>
        <td><%= nota.url %></td>
        <td><%= nota.website_id %></td>
        <td><%= nota.resumen_id %></td>
        <td><%=l nota.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_nota_path(nota), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      nota_path(nota),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_nota_path,
            :class => 'btn btn-primary' %>

app/views/notas/new.html.erb
<%- model_class = Nota -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/notas/show.html.erb
<%- model_class = Nota -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:titulo) %>:</strong></dt>
  <dd><%= @nota.titulo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contenido) %>:</strong></dt>
  <dd><%= @nota.contenido %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tipo_nota_id) %>:</strong></dt>
  <dd><%= @nota.tipo_nota_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @nota.url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:website_id) %>:</strong></dt>
  <dd><%= @nota.website_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:resume_id) %>:</strong></dt>
  <dd><%= @nota.resume_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              notas_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_nota_path(@nota), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              nota_path(@nota),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>