config/routes.rb
Dunamis::Application.routes.draw do

  
  resources :paginas

  resources :alertas do
    collection do
      get 'descargas'
    end
  end
  resources :tipos_alertas

  resources :usuarios

  resources :partidos

  resources :tipos_webnotas

  resources :posts

  resources :notas

  resources :tipos_notas

  resources :resumenes do
    collection do
      get 'paso1'
      get 'paso2'
      get 'unir'
      get 'separar'
      get 'descargar'      
    end
    resources :notas
    collection do
      get 'paso1'
      post 'paso1_guardar'
      get 'paso2'
      post 'paso2_guardar'
    end
  end

  resources :candidatos

  resources :tipos_cargos

  resources :municipios

  resources :voceros

  resources :elecciones

  

  resources :informes do
    collection do
      get 'enviar_por_correo'
      get 'paso1'
      get 'paso2'
      get 'paso2b'
      get 'paso3'
      get 'paso4'
      get 'paso5'
      get 'paso6'
      post 'agregar'
      get 'paso3_guardar'
      post 'desagregar_resumen'
    end
    resources :resumenes
  end

  resources :asuntos do
    resources :temas
  end

  resources :temas do
    resources :resumenes
  end

  resources :websites do
    collection do
      get 'barrer'
    end

    resources :paginas
  end

  resources :apariciones

  resources :cunas

  resources :organizaciones do
    match 'actualizar_select_municipios', :action => 'actualizar_select_municipios'
  end

  resources :estados do
    resources :municipios
  end

  resources :candidates

  get "home/index"

  match 'generar_reporte' => 'candidates#generar_reporte', :as => :generar_reporte
  
  match 'organizaciones/actualizar_select_municipios', :controller => 'organizaciones', :action => 'actualizar_select_municipios'

  root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/estado.rb
class Estado < ActiveRecord::Base
  attr_accessible :descripcion, :nombre, :nombre_corto
  validates_presence_of :nombre, :nombre_corto
  
  has_many :candidates
  accepts_nested_attributes_for :candidates
  
  has_many :municipios
  accepts_nested_attributes_for :municipios
  
  
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  # GET /estados
  # GET /estados.json
  before_filter :filtro_logueado
  def index
    @estados = Estado.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @estados }
    end
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
    @estado = Estado.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @estado }
    end
  end

  # GET /estados/new
  # GET /estados/new.json
  def new
    @estado = Estado.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @estado }
    end
  end

  # GET /estados/1/edit
  def edit
    @estado = Estado.find(params[:id])
  end

  # POST /estados
  # POST /estados.json
  def create
    @estado = Estado.new(params[:estado])

    respond_to do |format|
      if @estado.save
        format.html { redirect_to @estado, notice: 'Estado was successfully created.' }
        format.json { render json: @estado, status: :created, location: @estado }
      else
        format.html { render action: "new" }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /estados/1
  # PUT /estados/1.json
  def update
    @estado = Estado.find(params[:id])

    respond_to do |format|
      if @estado.update_attributes(params[:estado])
        format.html { redirect_to @estado, notice: 'Estado was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado = Estado.find(params[:id])
    @estado.destroy

    respond_to do |format|
      format.html { redirect_to estados_url }
      format.json { head :no_content }
    end
  end
  
  def actualizar_select_municipios
    @municipios = Municipio.where(:estado_id => params[:id])
    render :partial => "municipios", :municipios => @municipios
  end
  
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/views/estados/_form.html.erb
<%= form_for @estado, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :descripcion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :descripcion, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :nombre_corto, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre_corto, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                estados_path, :class => 'btn' %>
  </div>
<% end %>

app/views/estados/_municipios.html.erb
<%- unless @municipios.blank? %>
 <div class="control-group">
   <div class="controls">
			<%= label :municipio_id, "municipio" %>
			<%= collection_select :estado, :municipios, @municipios, :id, :nombre %>
   </div>
 </div>
<% end %>

app/views/estados/edit.html.erb
<%- model_class = Estado -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/estados/index.html.erb
<%- model_class = Estado -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:descripcion) %></th>
      <th><%= model_class.human_attribute_name(:nombre_corto) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @estados.each do |estado| %>
      <tr>
        <td><%= link_to estado.id, estado_path(estado) %></td>
        <td><%= estado.nombre %></td>
        <td><%= estado.descripcion %></td>
        <td><%= estado.nombre_corto %></td>
        <td><%=l estado.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_estado_path(estado), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      estado_path(estado),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_estado_path,
            :class => 'btn btn-primary' %>

app/views/estados/new.html.erb
<%- model_class = Estado -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/estados/show.html.erb
<%- model_class = Estado -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @estado.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descripcion) %>:</strong></dt>
  <dd><%= @estado.descripcion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nombre_corto) %>:</strong></dt>
  <dd><%= @estado.nombre_corto %></dd>
</dl>

<h3 id="municipios">Municipios</h3>
<% if @estado.municipios %>
	<% @estado.municipios.each do |municipio| -%>
		<h6><%= municipio.nombre -%></h6>
	<%- end -%>

	<%= form_for([@estado, @estado.municipios.build]) do |f| %>

  	<div class="control-group">
    	<div class="controls">
				<h6>Agregar municipio:
				<%= f.text_field :nombre, :class => 'input-medium', :placeholder => "Nombre…", :required => true %>
    		<%= f.submit nil, :class => 'btn btn-primary' %>
				</h6>
			</div>
  	</div>
	<% end %>
<% end %>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              estados_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_estado_path(@estado), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              estado_path(@estado),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>